### PR TITLE
Migration: Expo, File-base routing, State Managemente, Refactor, Best Practices & Guidelines, Tests, Documentation, Pin & Settings & More

### PR DESCRIPTION
**Pull request by Psycarlo**
Hello everyone 👋🏼 

This PR has a lot of things:
- Monorepo with [turborepo](https://turbo.build/repo)
- Use [expo](https://expo.dev/)
- File-base routing with [expo-router](https://docs.expo.dev/router/introduction/) (route type safe)
- Lint & Format improvements (ex.: sort imports)
- Refactor Components
- Refactor Screens
- Refactor Styles
- Refactor Utils
- Add layout components
- Localization ready (english only for now)
- State Management with [zustand](https://github.com/pmndrs/zustand) - Less boilerplate, Renders components only on changes, Centralized, action-based state management (comparing with context)
- Splash & Icons
- SF Pro Text font (remove SF Pro Display)
- Best Practices (ex.: useMemo to optimize re-renders) & Guidelines (ex.: component code structure)
- Unit tests with [jest](https://jestjs.io/)
- Documentation website with [nextra](https://nextra.site/)
- and more...

The proposed changes will increase:

- Readability
- Maintainability
- Testability
- Reusability

### CODE REVIEW

**Comment by Psycarlo** [comment]
Allow me to describe the changes

- Monorepo with turborepo

Now, satsigner repository is a monorepo. At the moment we have two apps: `mobile` and `docs`
To install dependencies, we install them in the root folder with `yarn install`

For now, we only have two turbo scripts: `lint` and `lint:format`
Turborepo will get more usefull as the project grows and we have more apps and packages, we start managing apps versions/changelogs/distributions and have more automated processes.

- Dependencies

A list of the mobile app dependencies and what they are used for:

| Dependency                     | Used for                                                             |
| ------------------------------ | -------------------------------------------------------------------- |
| @shopify/react-native-skia     | Utxo Bubbles                                                         |
| bdk-rn                         | Bitcoin Development Kit for React Native                             |
| bip39                          | Bip39 Word List                                                      |
| d3                             | Data manipulation for data visualization                             |
| expo                           | Framework to develop Android and iOS apps easier                     |
| expo-constants                 | Required by expo-router                                              |
| expo-font                      | Load SF Pro Text                                                     |
| expo-image                     | Load images (includes svgs)                                          |
| expo-linear-gradient           | Use LinearGradient                                                   |
| expo-linking                   | Required by expo-router                                              |
| expo-localization              | Localization                                                         |
| expo-navigation-bar            | Work with navigation bar                                             |
| expo-router                    | Navigation                                                           |
| expo-secure-store              | Store and read data in SharedPreferences (android) or Keychain (iOS) |
| expo-status-bar                | Work with status bar                                                 |
| expo-system-ui                 | To set backgroundColor                                               |
| expo-web-browser               | Open web links (used in SSLink)                                      |
| i18n-js                        | Localization strings                                                 |
| react                          | React                                                                |
| react-native                   | React Native                                                         |
| react-native-bouncy-checkbox   | Checkbox                                                             |
| react-native-gesture-handler   | Handle gestures (Utxo Bubbles)                                       |
| react-native-mmkv              | Fast storage solution                                                |
| react-native-reanimated        | Animations                                                           |
| react-native-safe-area-context | Required by expo-router                                              |
| react-native-screens           | Required by expo-router                                              |
| react-timeago                  | Help us to display timeago                                           |
| zustand                        | Simple State Management                                              |

- Expo Router

The `app` folder now serves as the file-base routing root folder for the satsigner mobile app.
Quickly create new pages by simply adding a file (or a folder and a file).

On each page, we can easily configure the header:

```tsx
<Stack.Screen
  options={{
    headerTitle: () => (
      <SSText uppercase>{accountStore.currentAccount.name}</SSText>
    )
  }}
/>
```

For more instructions, see [here](https://docs.expo.dev/router/create-pages/)

- Layouts

Layouts are just components that are used to create page layouts and standardize layouts across the app.
For example, if you want to display items in a flex column, use SSVStack:

```tsx
<SSVStack>
  <SSButton
    label={i18n.t('addMasterKey.generateNewSeed.action')}
    variant="secondary"
    disabled={!checksumValid}
    onPress={() => router.navigate('/addMasterKey/confirmSeed/0')}
  />
  <SSButton
    label={i18n.t('common.cancel')}
    variant="ghost"
    onPress={() => router.replace('/accountList/')}
  />
</SSVStack>
```

Check the available props before trying to override styles with the `style` prop.

- Localization

Strings now come from json files under `locales` folder
We can quickly add new languages to the app.

Here is an example on how to use these strings:

```tsx
<SSText size="xxs" style={{ color: Colors.gray[400] }}>
  {i18n.t('bitcoin.sats').toLowerCase()}
</SSText>
```

English only for now.

- Components

Components (and layouts) are now prefixed with "SS" so we can quickly distinguish them from other components.

Base styles are declared on the bottom of the file with:

```tsx
const styles = StyleSheet.create({
  buttonBase: {
    borderRadius: Sizes.button.borderRadius,
    height: Sizes.button.height,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
  },
  ...
)}
```

Styles that are conditional, based on props, are computed inside the component.

If you are going to write new components, first make sure if a new component is really needed or you can just place the code inside the page. Can we reuse the component or is it big enough/has enough logic to export to a new file?

Next, try to follow the examples so we can have consistency.

- State Management

We now use zustand for our state management solution.
Less boilerplate, Renders components only on changes, Centralized, action-based state management (comparing with context).

We have 4 stores for now: `accounts`, `blockchain`, `price`, `transactionBuilder`
Some stores auto-save/persist data using MMKV

| Store              | Used for                        | Auto save |
| ------------------ | ------------------------------- | --------- |
| accounts           | Manage stored accounts          | Yes       |
| blockchain         | Manage blockchain configuration | Yes       |
| price              | Bitcoin price in fiat currency  | No        |
| transactionBuilder | Construct transaction           | No        |

- Styles

Styles are now more organized. We can quickly change, for example, the border radius of all app buttons by just changing the value here:

```ts
export const button = {
  borderRadius: 3,
  height: 58,
  fontSize: text.fontSize.sm
}

// styles/sizes.ts
```

- Hooks

Custom hooks under `hooks` folder

- Utils

Utils are located under `utils` folder. We have some unit tests for some util functions.

- Types

Types are located under `types` folder

- Lint & Format

At the root of the repository, you can lint and format all apps/packages.
Lint uses `eslint` and format uses `prettier`

`yarn lint` - lints without trying to fix warnings
`yarn lint:fix` - lints and tries to fix warnings

`yarn format` - runs format check
`yarn format:fix` - runs prettier and tries to fix problems

When commiting changes, `husky` will trigger lint-staged - this will run `yarn lint:fix` and `yarn format:fix` automatically.

- Tests

For now, we have unit tests under `tests/unit`
Tests folder structure mimics the app folder structure

```bash
yarn test:unit
```

- Imports

We have an import alias '@'

```json
"paths": {
  "@/*": ["./*"]
}
```

```ts
import { type Utxo } from '@/types/models/Utxo'
```

===

This is just the start. Things can always be improved.
Feel free to give feedback and propose changes.
Let me know if I missed something.
Do not hesitate to contact me!

**Comment by umarluqman** [comment]
Great Job! This is a huge refactor and it is well done. I just tried with the munitynet (thanks to Tom) and it works pretty well for me. The styling is nicer and more streamlined especially for the UTXO bubbles.

As for the code structure, adding the SS in front of the component name is definitely for making importing easier.

I was wondering if let's say the we will be adding more custom hooks, do you think it's better to make a folder inside it to categorised the related hooks? 

Or do you think without folder is better? I personally inclined more towards having folder(s) inside a more general folder like components or hooks.

**Comment by umarluqman** [comment]
Other than that, LGFM!

**Comment by Psycarlo** [comment]
@umarluqman it's fine to create more folders inside the `hooks` folder and organize them like that.

**Comment by umarluqman** [comment]
I found out there is an inconsistency for the SSText in both utxo bubble screen and utxo list screen
Screenshot at Jun 13 12-05-58

I will be send a PR to fix it

**Comment by Psycarlo** [comment]
Added `PIN` and `Settings`

PIN features:
- setup can be skipped
- shakes if incorrect
- max tries
- stored in keychain

Settings icon in header top right

**Review by umarluqman — APPROVED** [review]
Approved

**Pull request merged**
