### PR TITLE
[REFACTOR]  Functional Components (Home | AccountsComponent)

### PR DESCRIPTION
**Pull request by Fahad-Mahmood**
1- Files Converted to Functional Components
- App.tsx
- HomeScreen.tsx
- AccountComponents.tsx

2- Svg files import typescript warning fix (type declaration added)

3- AppText component missing prop types (style prop)

4- Prettier bracket spacing added (most of the files were already using this).

### CODE REVIEW

**Comment by Psycarlo** [comment]
LGTM

**Review by Psycarlo — APPROVED** [review]

**Comment by tmakerman** [comment]
> * These styles are used by two files (AccountList, and AccountComponent). I'll see if I can separate them (in the next PR maybe when I convert AccountList component).

That would be great.

**Comment by tmakerman** [comment]
On the component called `AccountComponents`...  For components so far I have been adding `Screen` to end of component name but otherwise leaving `Component` out of component name.  Maybe `AccountComponents` could be renamed to `Accounts`?

**Comment by tmakerman** [comment]
@Fahad-Mahmood I'm done reviewing.  This looks great.  Just the comment above on AccountComponents naming.

**Review by tmakerman — CHANGES_REQUESTED** [review]
@Fahad-Mahmood I'm done reviewing.  This looks great.  Just the comment above on AccountComponents naming.

**Comment by Fahad-Mahmood** [comment]
nice idea.

**Review by tmakerman — CHANGES_REQUESTED** [review]
Sorry to be a pain :) but I think plural "Accounts" rather than "Account" as the component represents multiple accounts.

**Comment by Fahad-Mahmood** [comment]
oh, that's correct! we receive an array prop for accounts

**Comment by Fahad-Mahmood** [comment]
But I think we should create a separate directory for screens in the future.

**Comment by tmakerman** [comment]
> But I think we should create a separate directory for screens in the future.

I think that makes sense, especially when multiple files are needed for a screen.  I think it will be a good pattern.

**Comment by Fahad-Mahmood** [comment]
@Psycarlo @tmakerman Thanks for the review ❤️

**Pull request merged**
